// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    {
      type: "category",
      label: "Pendahuluan",
      collapsed: true,
      items: [
        "pendahuluan/apa-itu-kirimy",
        "pendahuluan/siapa-pengguna",
        "pendahuluan/fitur-unggulan",
      ],
    },
    {
      type: "category",
      label: "Mulai Cepat",
      collapsed: true,
      items: [
        "mulai-cepat/daftar-login",
        "mulai-cepat/aktivasi-whatsapp",
        "mulai-cepat/setup-blasting",
        "mulai-cepat/setup-ai-agent",
      ],
    },
    {
      type: "category",
      label: "Panduan Pengguna",
      collapsed: true,
      items: [
        "panduan-pengguna/blasting",
        "panduan-pengguna/chat-ai-agent",
        "panduan-pengguna/tiket",
        "panduan-pengguna/pengaturan-akun",
        "panduan-pengguna/faq",
      ],
    },
    {
      type: "category",
      label: "Panduan Developer (API)",
      collapsed: true,
      items: [
        "api-developer/pengantar-api",
        "api-developer/autentikasi",
        "api-developer/endpoint-blasting",
        "api-developer/endpoint-ai-agent",
        "api-developer/contoh-penggunaan",
        "api-developer/webhook",
      ],
    },
    {
      type: "category",
      label: "Referensi Teknis",
      collapsed: true,
      items: [
        "referensi/kode-error",
        "referensi/batasan",
        "referensi/changelog",
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
